# GenieUs Cloud Build Configuration with Environment File Support
# 環境変数ファイルベースのデプロイ設定

steps:
  # Step 1: 環境変数とプロジェクト設定
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔧 Cloud Build環境設定..."
        gcloud config set project $_GCP_PROJECT_ID
        echo "Project: $_GCP_PROJECT_ID"
        echo "Environment: $_ENVIRONMENT"
        echo "Region: $_GCP_REGION"

  # Step 2: 必要なAPIを有効化
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔌 必要なGCP APIを有効化中..."
        gcloud services enable run.googleapis.com
        gcloud services enable cloudbuild.googleapis.com
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable artifactregistry.googleapis.com
        gcloud services enable aiplatform.googleapis.com
        echo "✅ API有効化完了"

  # Step 3: バックエンドビルド・デプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🐍 バックエンドをデプロイ中..."
        
        cd backend
        
        # デプロイ実行
        echo "Backend Service: $_BACKEND_SERVICE_NAME"
        gcloud run deploy "$_BACKEND_SERVICE_NAME" \
          --source . \
          --platform managed \
          --region $_GCP_REGION \
          --allow-unauthenticated \
          --port 8080 \
          --cpu 1 \
          --memory 2Gi \
          --min-instances $_BACKEND_MIN_INSTANCES \
          --max-instances $_BACKEND_MAX_INSTANCES \
          --set-env-vars "GOOGLE_CLOUD_PROJECT=$_GCP_PROJECT_ID" \
          --set-env-vars "ENVIRONMENT=$_ENVIRONMENT" \
          --set-env-vars "GOOGLE_GENAI_USE_VERTEXAI=True" \
          --set-env-vars "GOOGLE_CLOUD_LOCATION=us-central1" \
          --set-env-vars "ROUTING_STRATEGY=$_ROUTING_STRATEGY" \
          --set-env-vars "LOG_LEVEL=$_LOG_LEVEL" \
          --set-env-vars "GOOGLE_API_KEY=$_GOOGLE_API_KEY" \
          --timeout 300 \
          --quiet
        
        # バックエンドURL取得
        BACKEND_URL=$(gcloud run services describe "$_BACKEND_SERVICE_NAME" \
          --platform managed \
          --region $_GCP_REGION \
          --format 'value(status.url)')
        
        echo "$BACKEND_URL" > /workspace/backend_url.txt
        echo "✅ バックエンドデプロイ完了: $BACKEND_URL"

  # Step 4: フロントエンドビルド・デプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "⚛️ フロントエンドをデプロイ中..."
        
        cd frontend
        
        # バックエンドURLを取得
        while [ ! -f /workspace/backend_url.txt ]; do
          echo "Waiting for backend URL..."
          sleep 5
        done
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        
        # デプロイ実行
        echo "Frontend Service: $_FRONTEND_SERVICE_NAME"
        echo "Backend URL: $BACKEND_URL"
        gcloud run deploy "$_FRONTEND_SERVICE_NAME" \
          --source . \
          --platform managed \
          --region $_GCP_REGION \
          --allow-unauthenticated \
          --port 3000 \
          --cpu 1 \
          --memory 1Gi \
          --min-instances $_FRONTEND_MIN_INSTANCES \
          --max-instances $_FRONTEND_MAX_INSTANCES \
          --set-env-vars "NODE_ENV=production" \
          --set-env-vars "NEXT_PUBLIC_API_BASE_URL=$BACKEND_URL" \
          --set-env-vars "NEXTAUTH_SECRET=$_NEXTAUTH_SECRET" \
          --set-env-vars "GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID" \
          --set-env-vars "GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET" \
          --timeout 300 \
          --quiet
        
        # フロントエンドURL取得
        FRONTEND_URL=$(gcloud run services describe "$_FRONTEND_SERVICE_NAME" \
          --platform managed \
          --region $_GCP_REGION \
          --format 'value(status.url)')
        
        echo "$FRONTEND_URL" > /workspace/frontend_url.txt
        
        # NEXTAUTH_URLを動的に更新
        echo "🔧 Updating NEXTAUTH_URL..."
        gcloud run services update "$_FRONTEND_SERVICE_NAME" \
          --region $_GCP_REGION \
          --update-env-vars "NEXTAUTH_URL=$FRONTEND_URL" \
          --quiet
        
        echo "✅ フロントエンドデプロイ完了: $FRONTEND_URL"
    waitFor: ['deploy-backend']

  # Step 5: バックエンドCORS設定更新
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'update-backend-cors'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔧 バックエンドのCORS設定を更新中..."
        
        FRONTEND_URL=$(cat /workspace/frontend_url.txt)
        # CORS_ORIGINSを更新
        gcloud run services update "$_BACKEND_SERVICE_NAME" \
          --region $_GCP_REGION \
          --update-env-vars "CORS_ORIGINS=$FRONTEND_URL" \
          --quiet
        
        echo "✅ CORS設定更新完了"
    waitFor: ['deploy-frontend']

  # Step 6: ヘルスチェック
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏥 ヘルスチェック実行中..."
        
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        FRONTEND_URL=$(cat /workspace/frontend_url.txt)
        
        # 少し待機（サービス起動待ち）
        sleep 10
        
        # バックエンドヘルスチェック
        echo "Checking backend health..."
        if curl -f "$BACKEND_URL/health" -m 30; then
          echo "✅ Backend health check OK"
        else
          echo "⚠️ Backend health check failed"
        fi
        
        # フロントエンドヘルスチェック
        echo "Checking frontend..."
        if curl -f "$FRONTEND_URL" -m 30 > /dev/null 2>&1; then
          echo "✅ Frontend health check OK"
        else
          echo "⚠️ Frontend health check failed"
        fi
        
        echo ""
        echo "🎉 デプロイ完了サマリー"
        echo "=========================="
        echo "Environment: $_ENVIRONMENT"
        echo "Project: $_GCP_PROJECT_ID"
        echo "Region: $_GCP_REGION"
        echo ""
        echo "Frontend URL: $FRONTEND_URL"
        echo "Backend URL: $BACKEND_URL"
        echo "API Docs: $BACKEND_URL/docs"
        echo "=========================="
    waitFor: ['update-backend-cors']

# 置換変数（deploy-with-env.shから渡される）
substitutions:
  _GCP_PROJECT_ID: 'your-project-id'
  _ENVIRONMENT: 'staging'
  _GCP_REGION: 'asia-northeast1'
  _BACKEND_SERVICE_NAME: 'genius-backend-staging'
  _FRONTEND_SERVICE_NAME: 'genius-frontend-staging'
  _ROUTING_STRATEGY: 'enhanced'
  _LOG_LEVEL: 'INFO'
  _NEXTAUTH_SECRET: 'default-nextauth-secret'
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _GOOGLE_API_KEY: ''
  _BACKEND_MIN_INSTANCES: '0'
  _BACKEND_MAX_INSTANCES: '3'
  _FRONTEND_MIN_INSTANCES: '0'
  _FRONTEND_MAX_INSTANCES: '5'

# ビルド設定
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  env:
    - 'CLOUDSDK_COMPUTE_REGION=$_GCP_REGION'
    - 'CLOUDSDK_RUN_REGION=$_GCP_REGION'